### ISSUE TITLE
Issue Generating Commit Message(Auto) when using Module.

### ISSUE THREAD

**Issue by glenson** [qirolab/spec-coder-issues#1]
In my project I have different Modules:
MainApp
- Modules\Core
- Modules\Academic
- Modules\Report
- Modules\Enroll

Each modules is pointing to different git repositories.
When I tried to use/click the Auto "Generate commit message" icon.
Example the Modules\Core repo.  I'm getting an error:
`Command failed: git diff --staged --minimal error: unknown option ...`

Which I got this same error if I manual run the command(git diff --staged --minimal) under the folder MainApp (because it is not a git folder).
But when I tried to run this command under Modules\Core through cli.  I don't get this error.

**Comment by glenson** [comment]
I found a workaround which is opening the Core(Module) folder in vscode instead of the MainApp folder.

**Comment by hkp22** [comment]
Your workaround of opening the module folder directly in VSCode instead of the MainApp folder is a practical solution. By doing so, VSCode can correctly identify the Git repository context and execute the commands without errors.
