### ISSUE TITLE
Error: Extension is not compatible with Code 1.85.2. Extension requires: ^1.87.0

### ISSUE THREAD

**Issue by yaddly** [qirolab/spec-coder-issues#2]
Good day, I'm getting an error saying Extension is not compatible with Code 1.85.2. Extension requires: ^1.87.0. Funny enough, VS Code does not have an update to upgrade to 1.87.0 as I'm already using the latest version.

![Screenshot 2024-07-15 141530](https://github.com/user-attachments/assets/4ab12953-98da-42f9-b01d-337439ed35f4)

**Comment by hkp22** [comment]
@yaddly You are using an old VSCode editor. Install the latest one and try it again.
